parameters:
  cegid:
    wsdl: '%env(CEGID_WSDL)%'
    login: '%env(CEGID_LOGIN)%'
    password: '%env(CEGID_PASSWORD)%'
    db_id: '%env(CEGID_DB_ID)%'
services:
  _defaults:
    autowire: true
    autoconfigure: true
  Colorz\CegidBundle\Service\Y2:
    class: Colorz\CegidBundle\Service\Y2
    arguments:
