parameters:
  cegid:
    wsdl: '%env(CEGID_WSDL)%'
    login: '%env(CEGID_LOGIN)%'
    password: '%env(CEGID_PASSWORD)%'
    db_id: '%env(CEGID_DB_ID)%'

services:
  Colorz\Cegid\Service\Y2:
    public: true
    tags:
      - 'colorz.cegid.y2'
    class: Colorz\Cegid\Service\Y2
    arguments:
